# Generated by Django 3.1.2 on 2020-10-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
