# Generated by Django 3.1.2 on 2020-10-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_box_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_amount',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='box_pay',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='box_size',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='box_value',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
