# Generated by Django 3.1.2 on 2020-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201022_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='box_latest',
            field=models.BooleanField(default=True),
        ),
    ]
