# Generated by Django 3.1.2 on 2020-10-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=200)),
                ('a_contents', models.TextField()),
                ('a_time', models.DateTimeField(auto_now=True)),
                ('a_qna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportapp.qna')),
            ],
        ),
    ]
