# Generated by Django 3.1.2 on 2020-10-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='today_f',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='qna',
            name='total',
            field=models.IntegerField(default='0'),
        ),
    ]
