# Generated by Django 3.1.2 on 2020-10-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0002_auto_20201018_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='today_f',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='total',
        ),
    ]
