# Generated by Django 3.1.2 on 2020-10-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='public',
            field=models.BooleanField(null=True),
        ),
    ]
